"""S3M-Core Platform Abstraction Layer — Common contracts and messages."""

from .messages import (
    AimSolution,
    AuthorityLevel,
    AuthorizationType,
    AutonomyMode,
    AutonomyRecommendation,
    EngagementRecommendation,
    FaultEvent,
    FaultSeverity,
    HealthState,
    InterlockState,
    MissionStatus,
    MissionTask,
    MissionTaskType,
    MobilityCommand,
    MobilityCommandType,
    OperatorAuthorization,
    PayloadState,
    PayloadType,
    PlatformState,
    PlatformType,
    ROEProfile,
    SensorCommand,
    SensorCommandType,
    ThreatPriority,
    Track,
)
from .contracts import PlatformAdapter, PayloadAdapter, PlatformCapabilities
from .health import HealthMonitor
from .capabilities import get_capabilities, CAPABILITY_REGISTRY

__all__ = [
    "AimSolution",
    "AuthorityLevel",
    "AuthorizationType",
    "AutonomyMode",
    "AutonomyRecommendation",
    "EngagementRecommendation",
    "FaultEvent",
    "FaultSeverity",
    "HealthState",
    "InterlockState",
    "MissionStatus",
    "MissionTask",
    "MissionTaskType",
    "MobilityCommand",
    "MobilityCommandType",
    "OperatorAuthorization",
    "PayloadState",
    "PayloadType",
    "PlatformState",
    "PlatformType",
    "ROEProfile",
    "SensorCommand",
    "SensorCommandType",
    "ThreatPriority",
    "Track",
    "PlatformAdapter",
    "PayloadAdapter",
    "PlatformCapabilities",
    "HealthMonitor",
    "get_capabilities",
    "CAPABILITY_REGISTRY",
]
