"""Shared platform abstraction messages for tactical mission control.

This module defines strongly-typed contracts used across platform adapters,
payload adapters, safety controls, and autonomy workflows in contested
operating environments.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
import math
import uuid
from typing import Any, Tuple


class PlatformType(Enum):
    """Vehicle domain used for mission routing and capability checks."""

    UGV = "ugv"
    UAV = "uav"
    USV = "usv"
    FIXED = "fixed"


class ThreatPriority(Enum):
    """Threat urgency level used to order engagement recommendations."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class MissionTaskType(Enum):
    """Mission taxonomy used by the mission executive."""

    PATROL = "patrol"
    RECON = "recon"
    HOLD = "hold"


class HealthState(Enum):
    """Platform health status used to gate tactical actions."""

    NOMINAL = "nominal"
    DEGRADED = "degraded"
    FAULT = "fault"


class MobilityCommandType(Enum):
    """Movement command vocabulary for tactical maneuver control."""

    MOVE_TO = "move_to"
    HOLD_POSITION = "hold_position"


class AuthorizationType(Enum):
    """Authorization category for controlled operator actions."""

    ARM = "arm"
    ENGAGE = "engage"
    MOBILITY = "mobility"


class AuthorityLevel(Enum):
    """Human command authority tiers for lethal-action governance."""

    OPERATOR = "operator"
    TEAM_LEAD = "team_lead"
    MISSION_COMMANDER = "mission_commander"


class InterlockState(Enum):
    """Safety interlock finite-state machine stages for weapon release."""

    SAFE = "safe"
    ARMED = "armed"
    FIRING = "firing"


class AutonomyMode(Enum):
    """Autonomy operating posture for human-machine teaming."""

    MANUAL = "manual"
    SUPERVISED = "supervised"
    AUTONOMOUS = "autonomous"


class ROEProfile(Enum):
    """Rules-of-engagement posture for force application constraints."""

    WEAPONS_HOLD = "weapons_hold"
    WEAPONS_TIGHT = "weapons_tight"
    WEAPONS_FREE = "weapons_free"


@dataclass
class Track:
    """Correlated tactical track produced by onboard or fused sensors."""

    track_id: str
    position: Tuple[float, float, float]
    confidence: float = 1.0
    classification: str = "unknown"
    threat_priority: ThreatPriority = ThreatPriority.MEDIUM
    last_seen: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __post_init__(self) -> None:
        if not self.track_id:
            raise ValueError("track_id must be a non-empty string")
        if len(self.position) != 3:
            raise ValueError("position must be a 3D tuple")
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError("confidence must be in [0, 1]")
        self.position = (
            float(self.position[0]),
            float(self.position[1]),
            float(self.position[2]),
        )

    def distance_to(self, other: "Track") -> float:
        """Compute Euclidean distance used for track association."""
        return math.dist(self.position, other.position)


@dataclass
class MissionTask:
    """Mission tasking message consumed by the mission executive."""

    task_type: MissionTaskType
    waypoints: list[Tuple[float, float, float]] = field(default_factory=list)
    parameters: dict[str, Any] = field(default_factory=dict)
    assigned_platform: str | None = None

    def __post_init__(self) -> None:
        normalized_waypoints: list[Tuple[float, float, float]] = []
        for waypoint in self.waypoints:
            if len(waypoint) != 3:
                raise ValueError("each waypoint must be a 3D tuple")
            normalized_waypoints.append((float(waypoint[0]), float(waypoint[1]), float(waypoint[2])))
        self.waypoints = normalized_waypoints
        if self.assigned_platform is not None and not self.assigned_platform:
            raise ValueError("assigned_platform must be a non-empty string when provided")


@dataclass
class PlatformState:
    """Platform status snapshot used for planning and safety decisions."""

    platform_id: str
    platform_type: PlatformType
    position: Tuple[float, float, float]
    health_state: HealthState = HealthState.NOMINAL
    autonomy_mode: AutonomyMode = AutonomyMode.SUPERVISED

    def __post_init__(self) -> None:
        if not self.platform_id:
            raise ValueError("platform_id must be a non-empty string")
        if len(self.position) != 3:
            raise ValueError("position must be a 3D tuple")
        self.position = (
            float(self.position[0]),
            float(self.position[1]),
            float(self.position[2]),
        )


@dataclass
class MobilityCommand:
    """Mobility command generated by mission logic for tactical movement."""

    command_type: MobilityCommandType
    target_position: Tuple[float, float, float] | None = None


@dataclass
class PayloadState:
    """Payload state for readiness and fire-control checks."""

    payload_id: str
    ammo_count: int
    connected: bool = False

    def __post_init__(self) -> None:
        if not self.payload_id:
            raise ValueError("payload_id must be a non-empty string")
        if self.ammo_count < 0:
            raise ValueError("ammo_count must be >= 0")


@dataclass
class OperatorAuthorization:
    """Operator action authorization with auditable unique identifier."""

    operator_id: str
    auth_type: AuthorizationType
    auth_id: str = field(default_factory=lambda: str(uuid.uuid4()))

    def __post_init__(self) -> None:
        if not self.operator_id:
            raise ValueError("operator_id must be a non-empty string")
